import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "@/components/ui/sonner";
import "./globals.css";
import { Card, CardContent } from "@/components/ui/card";
import AuthProvider from "./providers/auth";
import { PhoneVerificationWrapper } from "@/actions/phoneVerificationWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <PhoneVerificationWrapper>
            <div className="flex h-full flex-col">
              <div className="flex-1">{children}</div>
              <footer>
                <Card>
                  <CardContent className="py-2">
                    <p className="text-sm text-gray-400">
                      Todos direitos Reservados © Simply Barber
                    </p>
                  </CardContent>
                </Card>
              </footer>
            </div>
            <Toaster richColors />
          </PhoneVerificationWrapper>
        </AuthProvider>
      </body>
    </html>
  );
}
